# Generated by Django 3.0.7 on 2020-06-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MEgo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='ExpQuestions',
        ),
    ]
