# Generated by Django 3.0.7 on 2020-06-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MEgo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='Experience',
            new_name='experience',
        ),
    ]
