# Generated by Django 3.0.7 on 2020-06-19 18:38

import MEgo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEgo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='photo',
            field=models.ImageField(blank=True, upload_to=MEgo.models.user_path),
        ),
        migrations.AddField(
            model_name='experience',
            name='thumbnail_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
