# Generated by Django 3.0.7 on 2020-06-19 18:50

import MEgo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEgo', '0002_auto_20200620_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='thumbnail_photo',
            field=models.ImageField(blank=True, upload_to=MEgo.models.user_path),
        ),
    ]
