# Generated by Django 3.0.7 on 2020-07-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEgo', '0004_experience_emotion_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lifeiwish',
            old_name='goal_of_the_year',
            new_name='goal_of_the_year_2020',
        ),
        migrations.RemoveField(
            model_name='lifeiwish',
            name='life_values',
        ),
        migrations.RemoveField(
            model_name='lifeiwish',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='lifeiwish',
            name='year_of_the_goal',
        ),
        migrations.AddField(
            model_name='expquestions',
            name='answer_area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lifeiwish',
            name='goal_of_the_year_2030',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lifeiwish',
            name='goal_of_the_year_2040',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lifeiwish',
            name='goal_of_the_year_2050',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lifeiwish',
            name='life_values_high',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lifeiwish',
            name='life_values_low',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='thoughts',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lifeiwish',
            name='ideal_person',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lifeiwish',
            name='life_goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lifequestions',
            name='answer_area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lifequestions',
            name='related_tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
