# Generated by Django 3.0.7 on 2020-07-01 16:19

import MEgo.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MEgo', '0007_auto_20200701_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('wordcloud_event', models.ImageField(blank=True, null=True, upload_to=MEgo.models.user_path)),
                ('wordcloud_thought', models.ImageField(blank=True, null=True, upload_to=MEgo.models.user_path)),
                ('word_clustering', models.ImageField(blank=True, null=True, upload_to=MEgo.models.user_path)),
                ('social_map', models.ImageField(blank=True, null=True, upload_to=MEgo.models.user_path)),
                ('people_count', models.ImageField(blank=True, null=True, upload_to=MEgo.models.user_path)),
                ('things_joy', models.TextField(blank=True, null=True)),
                ('things_sadness', models.TextField(blank=True, null=True)),
                ('things_fear', models.TextField(blank=True, null=True)),
                ('pos_people_close', models.TextField(blank=True, null=True)),
                ('pos_people_far', models.TextField(blank=True, null=True)),
                ('neg_people_close', models.TextField(blank=True, null=True)),
                ('neg_people_far', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
