# Generated by Django 3.0.7 on 2020-06-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEgo', '0003_emotioncolor_lifeiwish_lifequestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='emotion_color',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
