# Generated by Django 3.0.7 on 2020-06-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEgo', '0004_experience_emotion_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='expquestions',
            name='answer_area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='thoughts',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lifeiwish',
            name='ideal_person',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lifeiwish',
            name='life_goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lifeiwish',
            name='life_values',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lifeiwish',
            name='priority',
            field=models.TextField(blank=True, null=True),
        ),
    ]
