# Generated by Django 3.0.7 on 2020-06-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEgo', '0006_auto_20200701_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifequestions',
            name='answer_area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lifequestions',
            name='related_tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
