# Generated by Django 3.0.7 on 2020-07-01 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MEgo', '0007_auto_20200701_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifeiwish',
            name='author',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
